[profile]
name = "yceachan"
tagline = "As Eachan's Views"
email = "yceachan@foxmail.com"
github = "https://github.com/yceachan"
repository = "https://github.com/yceachan/ea-md-reader"
copyright = "copyright (c) 2026 yceachan"
license = "MIT LICENSE"
profile-photo = "profile-photo.jpg"
