const { expect } = require('@playwright/test');
const { test, launch, close, chooseEditor } = require('./electron-fixture.cjs');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const platformArgs = process.platform === 'linux' ? ['--ozone-platform=x11'] : [];

test('文件树中键与非活动标签菜单编辑正确目标，同路径标签自动更新而标签中键只关闭', async () => {
  const directory = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'emd-editors-ui-')));
  let application;
  try {
    const sourceDirectory = path.join(directory, '文件'); await fs.mkdir(sourceDirectory);
    const file = path.join(sourceDirectory, '中文 空格 $()&.md'), other = path.join(sourceDirectory, '其他.md');
    const output = path.join(directory, 'launches.json');
    const script = `/*\n# 原始正文\n*/\nconst fs=require('node:fs');\nconst output=${JSON.stringify(output)};\nconst runs=fs.existsSync(output)?JSON.parse(fs.readFileSync(output,'utf8')):[];\nruns.push(process.argv[1]);fs.writeFileSync(output,JSON.stringify(runs));\nsetTimeout(()=>fs.writeFileSync(process.argv[1],fs.readFileSync(process.argv[1],'utf8').replace('原始正文','编辑后正文')),120);\n`;
    await fs.writeFile(file, script + `\n/*\n${'阅读正文段落。\n\n'.repeat(100)}\n*/\n`); await fs.writeFile(other, '# 其他文档\n');
    application = await launch({ args: [path.resolve('.'), ...platformArgs, `--user-data-dir=${path.join(directory, 'profile')}`, file, other] });
    const page = await application.firstWindow();
    await expect(page.getByRole('tab')).toHaveCount(2);
    if (await page.getByRole('button', { name: '显示工作区', exact: true }).getAttribute('aria-pressed') === 'false') await page.getByRole('button', { name: '显示工作区', exact: true }).click();
    await page.getByRole('button', { name: '显示目录', exact: true }).click();
    await page.getByRole('treeitem', { name: `MD ${path.basename(file)}` }).click({ button: 'middle' });
    const settings = page.getByRole('dialog', { name: '设置', exact: true });
    await expect(settings.getByRole('alert')).toContainText('请先配置 Markdown 编辑器');
    const executable = await fs.realpath(process.execPath);
    await chooseEditor(application, executable);
    await settings.getByRole('button', { name: '选择应用…' }).first().click();
    await expect(settings.getByRole('alert')).toHaveCount(0);
    await settings.getByRole('button', { name: '完成', exact: true }).click();
    await page.getByRole('treeitem', { name: `MD ${path.basename(file)}` }).click({ modifiers: ['Alt'] });
    await expect(page.getByRole('tab')).toHaveCount(3);
    await page.getByRole('tab', { name: 'MD 其他.md' }).click();
    const active = await page.getByRole('tab', { selected: true }).getAttribute('id');
    await application.evaluate(({ Menu }) => {
      const original = Menu.buildFromTemplate;
      Menu.buildFromTemplate = (template) => { const menu = original(template); menu.popup = () => { global.editorMenu = menu; }; return menu; };
    });
    await page.getByRole('tab').first().click({ button: 'right' });
    await expect.poll(() => application.evaluate(() => global.editorMenu?.items.map((item) => item.label))).toEqual(['在配置编辑器中打开', '打开方式…', '', '复制路径', '复制相对路径', '', '关闭标签页']);
    await application.evaluate(() => global.editorMenu.items[0].click());
    await expect.poll(async () => { try { return JSON.parse(await fs.readFile(output, 'utf8')); } catch (error) { if (error.code === 'ENOENT') return []; throw error; } }).toEqual([file]);
    await expect(page.locator('.document-panel h1').filter({ hasText: '编辑后正文' })).toHaveCount(2);
    await expect(page.getByRole('tab', { selected: true })).toHaveAttribute('id', active);
    await expect(page.locator('.document-panel:not([hidden]) h1')).toHaveText('其他文档');
    await page.getByRole('treeitem', { name: `MD ${path.basename(file)}` }).click({ button: 'middle' });
    await expect.poll(async () => JSON.parse(await fs.readFile(output, 'utf8'))).toEqual([file, file]);
    await expect.poll(async () => (await fs.readFile(file, 'utf8')).includes("replace('编辑后正文','编辑后正文')")).toBe(true);
    await page.getByRole('tab').last().click();
    const panel = page.locator('.document-panel:not([hidden])');
    await panel.evaluate((element) => { element.scrollTop = 300; });
    await fs.writeFile(file, (await fs.readFile(file, 'utf8')).replace('# 编辑后正文', '# 保存后正文'));
    await expect(panel.locator('h1')).toHaveText('保存后正文');
    await expect.poll(() => panel.evaluate((element) => element.scrollTop)).toBe(300);
    const progress = await panel.evaluate((element) => Math.round(element.scrollTop / (element.scrollHeight - element.clientHeight) * 100));
    await expect(page.locator('.progress')).toHaveText(`${progress}%`);
    await page.getByRole('tab', { name: 'MD 其他.md' }).click();
    await page.getByRole('tab').first().click({ button: 'middle' });
    await expect(page.getByRole('tab')).toHaveCount(2);
    await expect(page.getByRole('tab', { selected: true })).toHaveAttribute('id', active);
    await page.getByRole('tab').last().click({ button: 'right' });
    await chooseEditor(application, null);
    await application.evaluate(() => global.editorMenu.items[1].click());
    expect((await page.evaluate(() => window.emd.settings())).editors.markdown.program).toBe(executable);
    const temporaryDefault = await fs.realpath(process.platform === 'win32' ? path.join(process.env.SystemRoot, 'System32', 'whoami.exe') : '/usr/bin/true');
    await page.getByRole('button', { name: '设置', exact: true }).click();
    await chooseEditor(application, temporaryDefault);
    await settings.getByRole('button', { name: '选择应用…' }).first().click();
    await expect(settings.locator('.editor-setting').first()).toContainText(temporaryDefault);
    await settings.getByRole('button', { name: '完成', exact: true }).click();
    await chooseEditor(application, executable);
    await page.getByRole('tab').last().click({ button: 'right' });
    await application.evaluate(() => global.editorMenu.items[1].click());
    await expect.poll(async () => JSON.parse(await fs.readFile(output, 'utf8'))).toEqual([file, file, file]);
    expect((await page.evaluate(() => window.emd.settings())).editors.markdown.program).toBe(temporaryDefault);
    await expect(page.getByRole('alert')).toHaveCount(0);
  } finally {
    if (application) await close(application);
    await fs.rm(directory, { recursive: true, force: true });
  }
});
