cmake_minimum_required(VERSION 3.16)
project(emd_application_chooser LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_AUTOMOC ON)
find_package(KF6KIO QUIET)
if(KF6KIO_FOUND)
  set(KIO_PREFIX KF6)
  set(QT_PREFIX Qt6)
else()
  find_package(KF5KIO 5.71 REQUIRED)
  set(KIO_PREFIX KF5)
  set(QT_PREFIX Qt5)
endif()
add_executable(emd-application-chooser application-chooser.cpp)
target_link_libraries(emd-application-chooser PRIVATE ${KIO_PREFIX}::KIOWidgets)
find_package(${QT_PREFIX} REQUIRED COMPONENTS Core DBus)
add_executable(emd-kde-startup kde-startup.cpp)
target_link_libraries(emd-kde-startup PRIVATE ${QT_PREFIX}::Core ${QT_PREFIX}::DBus)
